server:
  port: 8080

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: dev
  application:
    name: ai-interview
  config:
    import:
      - classpath:redis-cache.yml

# JWT 配置（全局通用，敏感信息建议放 profile）
jwt:
  secret: ${JWT_SECRET:初时的本地配置文件chushi2333的密钥为什么chushi2333的密钥是可以的因为他是chushi2333}
  expiration: 604800

# MyBatis 全局配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

# SpringDoc 全局配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# 日志全局配置
logging:
  level:
    com.chushi.aiinterview: DEBUG
    org.mybatis: DEBUG
